"""
Shadow Parsing Comparator for ULPF-X (SIH26156) - Stage 17.
Evaluates active-vs-candidate parser outputs across:
- Field match rates and divergences
- Critical security semantics
- Unknown field retention (Rule 4)
- Detection Preservation Score (DPS)
- Execution latency
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional, Set, Tuple


class ShadowState(str, Enum):
    PASSED = "PASSED"
    FAILED = "FAILED"
    SUSPECTED = "SUSPECTED"


class ShadowRecommendation(str, Enum):
    READY_FOR_PROMOTION = "READY_FOR_PROMOTION"
    REJECT = "REJECT"
    REQUIRE_HUMAN_REVIEW = "REQUIRE_HUMAN_REVIEW"


@dataclass(frozen=True)
class ShadowMetrics:
    """Quantitative performance and accuracy metrics comparing active and candidate parsers."""
    field_match_rate: float
    critical_semantic_divergence: float
    unknown_field_retention: float
    active_dps: float
    candidate_dps: float
    dps_delta: float
    active_latency_p95_ms: float
    candidate_latency_p95_ms: float
    latency_delta_pct: float

    def to_dict(self) -> Dict[str, Any]:
        return {
            "field_match_rate": round(self.field_match_rate, 4),
            "critical_semantic_divergence": round(self.critical_semantic_divergence, 4),
            "unknown_field_retention": round(self.unknown_field_retention, 4),
            "active_dps": round(self.active_dps, 4),
            "candidate_dps": round(self.candidate_dps, 4),
            "dps_delta": round(self.dps_delta, 4),
            "active_latency_p95_ms": round(self.active_latency_p95_ms, 4),
            "candidate_latency_p95_ms": round(self.candidate_latency_p95_ms, 4),
            "latency_delta_pct": round(self.latency_delta_pct, 2),
        }


@dataclass(frozen=True)
class FieldDivergence:
    """Details of a field-level divergence observed between active and candidate."""
    field: str
    match_rate: float
    divergence_type: str  # VALUE_MISMATCH, FIELD_MISSING_IN_CANDIDATE, NEW_FIELD_IN_CANDIDATE, TYPE_MISMATCH
    example_mismatch: Optional[Dict[str, Any]] = None

    def to_dict(self) -> Dict[str, Any]:
        res: Dict[str, Any] = {
            "field": self.field,
            "match_rate": round(self.match_rate, 4),
            "divergence_type": self.divergence_type,
        }
        if self.example_mismatch is not None:
            res["example_mismatch"] = self.example_mismatch
        return res


@dataclass(frozen=True)
class ShadowComparisonReport:
    """Machine-readable assessment conforming to packages/contracts/shadow_comparison.schema.json."""
    source_id: str
    active_parser_id: str
    active_parser_version: str
    candidate_parser_id: str
    candidate_parser_version: str
    shadow_state: ShadowState
    evaluated_at: datetime
    start_time: datetime
    end_time: datetime
    sample_count: int
    metrics: ShadowMetrics
    field_divergences: List[FieldDivergence]
    downstream_isolation_verified: bool
    recommendation: ShadowRecommendation
    recommendation_reasons: List[str]

    def to_dict(self) -> Dict[str, Any]:
        """Converts report to dict conforming to packages/contracts/shadow_comparison.schema.json."""
        def iso_ts(dt: datetime) -> str:
            if dt.tzinfo is None:
                dt = dt.replace(tzinfo=timezone.utc)
            return dt.astimezone(timezone.utc).isoformat().replace("+00:00", "Z")

        return {
            "schema_version": "1.0",
            "source_id": self.source_id,
            "active_parser": {
                "id": self.active_parser_id,
                "version": self.active_parser_version,
            },
            "candidate_parser": {
                "id": self.candidate_parser_id,
                "version": self.candidate_parser_version,
            },
            "shadow_state": self.shadow_state.value,
            "evaluated_at": iso_ts(self.evaluated_at),
            "evaluation_window": {
                "start_time": iso_ts(self.start_time),
                "end_time": iso_ts(self.end_time),
                "sample_count": self.sample_count,
            },
            "metrics": self.metrics.to_dict(),
            "field_divergences": [fd.to_dict() for fd in self.field_divergences],
            "downstream_isolation_verified": self.downstream_isolation_verified,
            "recommendation": self.recommendation.value,
            "recommendation_reasons": list(self.recommendation_reasons),
        }


class ShadowComparator:
    """
    Compares outputs generated by active vs candidate parsers across an evaluation window.
    Evaluates field congruence, security semantics, unknown field retention, DPS, and latency.
    """

    CRITICAL_SECURITY_FIELDS = {
        "src.ip",
        "dst.ip",
        "src.port",
        "dst.port",
        "event.action",
        "event.outcome",
        "user.name",
    }

    def compare(
        self,
        source_id: str,
        active_parser_id: str,
        active_parser_version: str,
        candidate_parser_id: str,
        candidate_parser_version: str,
        active_events: List[Dict[str, Any]],
        candidate_events: List[Dict[str, Any]],
        active_latencies_ms: Optional[List[float]] = None,
        candidate_latencies_ms: Optional[List[float]] = None,
        downstream_isolation_verified: bool = True,
        start_time: Optional[datetime] = None,
        end_time: Optional[datetime] = None,
        evaluated_at: Optional[datetime] = None,
    ) -> ShadowComparisonReport:
        """
        Executes active vs candidate comparative analysis.
        """
        now = evaluated_at or datetime.now(timezone.utc)
        win_start = start_time or now
        win_end = end_time or now
        sample_count = max(len(active_events), len(candidate_events))

        reasons: List[str] = []

        # 1. Field-by-field match rate & divergence calculation
        field_match_rate, divergences = self._evaluate_field_congruence(
            active_events, candidate_events
        )

        # 2. Critical semantic divergence
        crit_divergence, crit_details = self._evaluate_critical_semantics(
            active_events, candidate_events
        )

        # 3. Unknown field retention (Rule 4)
        unknown_retention, unknown_details = self._evaluate_unknown_retention(
            active_events, candidate_events
        )

        # 4. Detection Preservation Score (DPS) comparison
        active_dps, candidate_dps, dps_delta, dps_details = self._evaluate_dps_comparison(
            active_events, candidate_events
        )

        # 5. Latency metrics
        active_p95, candidate_p95, lat_delta_pct, lat_details = self._evaluate_latencies(
            active_latencies_ms or [1.0], candidate_latencies_ms or [1.0]
        )

        # Compile metrics object
        metrics = ShadowMetrics(
            field_match_rate=field_match_rate,
            critical_semantic_divergence=crit_divergence,
            unknown_field_retention=unknown_retention,
            active_dps=active_dps,
            candidate_dps=candidate_dps,
            dps_delta=dps_delta,
            active_latency_p95_ms=active_p95,
            candidate_latency_p95_ms=candidate_p95,
            latency_delta_pct=lat_delta_pct,
        )

        # 6. Recommendation & State evaluation (PRD Section 9 refusal conditions)
        failure_flags: List[str] = []
        suspected_flags: List[str] = []

        if not downstream_isolation_verified:
            failure_flags.append("Downstream isolation violation: candidate output escaped to downstream bus")

        if dps_delta < 0:
            failure_flags.append(f"DPS regression detected: candidate DPS {candidate_dps:.2%} is lower than active DPS {active_dps:.2%}")

        if crit_divergence > 0:
            failure_flags.append(f"Critical semantic divergence {crit_divergence:.2%} exceeds 0% tolerance")

        if unknown_retention < 1.0:
            failure_flags.append(f"Unknown field retention {unknown_retention:.2%} violates Rule 4 (100% required)")

        if field_match_rate < 0.90:
            failure_flags.append(f"Field match rate {field_match_rate:.2%} is below acceptable baseline (90%)")
        elif field_match_rate < 0.98:
            suspected_flags.append(f"Field match rate {field_match_rate:.2%} requires review (between 90% and 98%)")

        abs_lat_delta = candidate_p95 - active_p95
        if lat_delta_pct > 50.0 and abs_lat_delta > 1.0:
            suspected_flags.append(f"Latency regression +{lat_delta_pct:.1f}% ({abs_lat_delta:.2f}ms) exceeds 50% threshold")

        # Determine shadow state and recommendation
        if failure_flags:
            shadow_state = ShadowState.FAILED
            recommendation = ShadowRecommendation.REJECT
            reasons.extend(failure_flags)
            if crit_details:
                reasons.extend(crit_details)
            if dps_details:
                reasons.extend(dps_details)
            if unknown_details:
                reasons.extend(unknown_details)
        elif suspected_flags:
            shadow_state = ShadowState.SUSPECTED
            recommendation = ShadowRecommendation.REQUIRE_HUMAN_REVIEW
            reasons.extend(suspected_flags)
            if lat_details:
                reasons.extend(lat_details)
        else:
            shadow_state = ShadowState.PASSED
            recommendation = ShadowRecommendation.READY_FOR_PROMOTION
            reasons.append("Zero critical semantic divergence observed across evaluation window")
            reasons.append(f"Detection preservation score (DPS) fully preserved at {candidate_dps:.2%}")
            reasons.append("Unknown field retention maintained at 100%")
            reasons.append(f"p95 latency delta: {lat_delta_pct:+.1f}% ({candidate_p95:.2f}ms vs active {active_p95:.2f}ms)")
            reasons.append("Downstream bus isolation successfully verified")

        return ShadowComparisonReport(
            source_id=source_id,
            active_parser_id=active_parser_id,
            active_parser_version=active_parser_version,
            candidate_parser_id=candidate_parser_id,
            candidate_parser_version=candidate_parser_version,
            shadow_state=shadow_state,
            evaluated_at=now,
            start_time=win_start,
            end_time=win_end,
            sample_count=sample_count,
            metrics=metrics,
            field_divergences=divergences,
            downstream_isolation_verified=downstream_isolation_verified,
            recommendation=recommendation,
            recommendation_reasons=reasons,
        )

    def _flatten_event(self, event: Dict[str, Any], prefix: str = "") -> Dict[str, Any]:
        """Flattens nested event objects into dot-notated dictionary keys."""
        flat: Dict[str, Any] = {}
        for k, v in event.items():
            if k.startswith("_") or k == "unknown_fields":
                continue
            full_k = f"{prefix}.{k}" if prefix else k
            if isinstance(v, dict):
                flat.update(self._flatten_event(v, full_k))
            else:
                flat[full_k] = v
        return flat

    def _evaluate_field_congruence(
        self, active_events: List[Dict[str, Any]], candidate_events: List[Dict[str, Any]]
    ) -> Tuple[float, List[FieldDivergence]]:
        """Calculates field-by-field match rate and identifies divergence details."""
        if not active_events or not candidate_events:
            return 1.0, []

        sample_len = min(len(active_events), len(candidate_events))
        field_match_counts: Dict[str, int] = {}
        field_total_counts: Dict[str, int] = {}
        field_divergence_examples: Dict[str, Tuple[str, Dict[str, Any]]] = {}

        total_active_comparisons = 0
        total_active_matches = 0

        for i in range(sample_len):
            act_flat = self._flatten_event(active_events[i])
            cand_flat = self._flatten_event(candidate_events[i])

            # Check active keys against candidate
            for k, val_act in act_flat.items():
                field_total_counts[k] = field_total_counts.get(k, 0) + 1
                total_active_comparisons += 1

                if k in cand_flat:
                    val_cand = cand_flat[k]
                    if val_act == val_cand:
                        field_match_counts[k] = field_match_counts.get(k, 0) + 1
                        total_active_matches += 1
                    else:
                        div_type = "TYPE_MISMATCH" if type(val_act) is not type(val_cand) else "VALUE_MISMATCH"
                        if k not in field_divergence_examples:
                            field_divergence_examples[k] = (div_type, {"active": val_act, "candidate": val_cand})
                else:
                    if k not in field_divergence_examples:
                        field_divergence_examples[k] = ("FIELD_MISSING_IN_CANDIDATE", {"active": val_act, "candidate": None})

            # Check new keys added by candidate
            for k, val_cand in cand_flat.items():
                if k not in act_flat:
                    if k not in field_divergence_examples:
                        field_divergence_examples[k] = ("NEW_FIELD_IN_CANDIDATE", {"active": None, "candidate": val_cand})
                    if k not in field_total_counts:
                        field_total_counts[k] = 1
                        field_match_counts[k] = 1

        overall_match_rate = (
            total_active_matches / total_active_comparisons if total_active_comparisons > 0 else 1.0
        )

        divergences: List[FieldDivergence] = []
        for field_name, total_cnt in sorted(field_total_counts.items()):
            if field_name in field_divergence_examples:
                div_type, ex_mismatch = field_divergence_examples[field_name]
                if div_type == "NEW_FIELD_IN_CANDIDATE":
                    rate = 1.0
                else:
                    rate = field_match_counts.get(field_name, 0) / total_cnt
                divergences.append(
                    FieldDivergence(
                        field=field_name,
                        match_rate=round(rate, 4),
                        divergence_type=div_type,
                        example_mismatch=ex_mismatch,
                    )
                )

        return round(overall_match_rate, 4), divergences

    def _evaluate_critical_semantics(
        self, active_events: List[Dict[str, Any]], candidate_events: List[Dict[str, Any]]
    ) -> Tuple[float, List[str]]:
        """Measures semantic divergence across critical security fields (IP, port, action, outcome, user)."""
        if not active_events or not candidate_events:
            return 0.0, []

        sample_len = min(len(active_events), len(candidate_events))
        crit_divergence_count = 0
        details: List[str] = []

        for i in range(sample_len):
            act_flat = self._flatten_event(active_events[i])
            cand_flat = self._flatten_event(candidate_events[i])

            event_diverged = False
            for crit_field in self.CRITICAL_SECURITY_FIELDS:
                act_val = act_flat.get(crit_field)
                cand_val = cand_flat.get(crit_field)

                if act_val is not None and cand_val is not None:
                    # Case insensitive for action/outcome strings
                    if crit_field in ("event.action", "event.outcome") and isinstance(act_val, str) and isinstance(cand_val, str):
                        if act_val.strip().lower() != cand_val.strip().lower():
                            event_diverged = True
                            if len(details) < 5:
                                details.append(
                                    f"Event #{i}: Critical '{crit_field}' diverged (active='{act_val}', candidate='{cand_val}')"
                                )
                    elif act_val != cand_val:
                        event_diverged = True
                        if len(details) < 5:
                            details.append(
                                f"Event #{i}: Critical '{crit_field}' diverged (active='{act_val}', candidate='{cand_val}')"
                            )
                elif act_val is not None and cand_val is None:
                    event_diverged = True
                    if len(details) < 5:
                        details.append(f"Event #{i}: Critical field '{crit_field}' dropped in candidate")

            if event_diverged:
                crit_divergence_count += 1

        divergence_rate = crit_divergence_count / sample_len if sample_len > 0 else 0.0
        return round(divergence_rate, 4), details

    def _evaluate_unknown_retention(
        self, active_events: List[Dict[str, Any]], candidate_events: List[Dict[str, Any]]
    ) -> Tuple[float, List[str]]:
        """Ensures candidate preserves unknown/unmapped fields without dropping them (Rule 4)."""
        if not active_events or not candidate_events:
            return 1.0, []

        sample_len = min(len(active_events), len(candidate_events))
        active_unknown_count = 0
        candidate_unknown_retained = 0
        details: List[str] = []

        for i in range(sample_len):
            act_unknown = active_events[i].get("unknown_fields") or {}
            cand_unknown = candidate_events[i].get("unknown_fields") or {}
            cand_flat = self._flatten_event(candidate_events[i])

            if isinstance(act_unknown, dict) and act_unknown:
                for k, v in act_unknown.items():
                    active_unknown_count += 1
                    # Retained if still in candidate's unknown_fields or mapped into candidate event
                    is_in_cand_unknown = isinstance(cand_unknown, dict) and k in cand_unknown
                    is_mapped_in_cand = any(val == v for val in cand_flat.values())
                    if is_in_cand_unknown or is_mapped_in_cand:
                        candidate_unknown_retained += 1
                    else:
                        if len(details) < 5:
                            details.append(f"Event #{i}: Unknown field '{k}' dropped in candidate")

        if active_unknown_count == 0:
            return 1.0, []

        retention_ratio = candidate_unknown_retained / active_unknown_count
        return round(retention_ratio, 4), details

    def _evaluate_dps_comparison(
        self, active_events: List[Dict[str, Any]], candidate_events: List[Dict[str, Any]]
    ) -> Tuple[float, float, float, List[str]]:
        """Evaluates Detection Preservation Score across active and candidate event sets."""
        details: List[str] = []

        def calc_dps(events: List[Dict[str, Any]]) -> float:
            expected = 0
            preserved = 0
            for ev in events:
                ev_obj = ev.get("event") if isinstance(ev.get("event"), dict) else {}
                action = str(ev_obj.get("action") or ev.get("event.action") or "").lower()
                outcome = str(ev_obj.get("outcome") or ev.get("event.outcome") or "").lower()
                src_ip = ev.get("src.ip") or ((ev.get("src") or {}).get("ip") if isinstance(ev.get("src"), dict) else None)
                dst_ip = ev.get("dst.ip") or ((ev.get("dst") or {}).get("ip") if isinstance(ev.get("dst"), dict) else None)

                is_security_event = "deny" in action or "block" in action or "drop" in action or "denied" in outcome
                if is_security_event:
                    expected += 1
                    if ("block" in action or "deny" in action or "drop" in action or "denied" in outcome) and (src_ip or dst_ip):
                        preserved += 1
            return (preserved / expected) if expected > 0 else 1.0

        active_dps = round(calc_dps(active_events), 4)
        candidate_dps = round(calc_dps(candidate_events), 4)
        dps_delta = round(candidate_dps - active_dps, 4)

        if dps_delta < 0:
            details.append(
                f"Candidate DPS ({candidate_dps:.2%}) regressed by {abs(dps_delta):.2%} compared to active DPS ({active_dps:.2%})"
            )

        return active_dps, candidate_dps, dps_delta, details

    def _evaluate_latencies(
        self, active_latencies_ms: List[float], candidate_latencies_ms: List[float]
    ) -> Tuple[float, float, float, List[str]]:
        """Computes p95 latencies and relative delta percentage."""
        details: List[str] = []

        def p95(latencies: List[float]) -> float:
            if not latencies:
                return 0.0
            sorted_lat = sorted(latencies)
            idx = int(len(sorted_lat) * 0.95)
            idx = min(idx, len(sorted_lat) - 1)
            return sorted_lat[idx]

        act_p95 = p95(active_latencies_ms)
        cand_p95 = p95(candidate_latencies_ms)

        if act_p95 > 0:
            lat_delta_pct = ((cand_p95 - act_p95) / act_p95) * 100.0
        else:
            lat_delta_pct = 0.0

        if lat_delta_pct > 20.0 and (cand_p95 - act_p95) > 1.0:
            details.append(f"Candidate p95 latency increased by {lat_delta_pct:.1f}% ({cand_p95:.2f}ms vs {act_p95:.2f}ms)")

        return round(act_p95, 4), round(cand_p95, 4), round(lat_delta_pct, 2), details
